name: CI Pipeline

on:
  push:
    branches: [ main - develop ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r vote/requirements.txt

      - name: Run flake8 lint
        run: flake8 vote/app.py vote/tests/

      - name: Run Python tests
        run: |
          python -m unittest discover -s vote/tests

  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (result)
        run: |
          cd result
          npm install

      - name: Run JS tests (result)
        run: |
          cd result
          npm test

      - name: Install dependencies (worker)
        run: |
          cd worker
          npm install

      - name: Run JS tests (worker)
        run: |
          cd worker
          npm test