name: Health Check

on:
  schedule:
    - cron: '*/30 * * * *' # Cada 30 minutos

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run health check (main)
        run: bash scripts/health-check.sh main
